### ISSUE TITLE
Problem with a custom adapter

### ISSUE THREAD

**Issue by tuanth89** [seatgeek/android-PlacesAutocompleteTextView#12]
Hi everyone! First, awesome library. I realy like it.
I try create a custom a adapter and passing it to my xml, however i get a error occurs at run activity.
How to fix this bug? Thanks

Here is my xml
<pre>
com.seatgeek.placesautocomplete.PlacesAutocompleteTextView
                            android:id="@+id/places_autocomplete"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            app:pacv_googleMapsApiKey="@string/API_server_key"
                        app:pacv_adapterClass="adapter.TestPlacesAutocompleteAdapter"
</pre>

Here is log

<pre>
Caused by: android.view.InflateException: Unable to find valid constructor with params Context, PlacesApi, AutocompleteResultType, and DefaultAutocompleteHistoryManager for specified adapterClass: com.teusoft.sirved.adapter.TestPlacesAutocompleteAdapter
                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.adapterForClass(PlacesAutocompleteTextView.java:225)
                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.init(PlacesAutocompleteTextView.java:127)
                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.(PlacesAutocompleteTextView.java:78)
                                           at java.lang.reflect.Constructor.newInstance(Native Method) 
                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
</pre>

**Comment by sddamico** [comment]
As documented in the `README`, to use a custom adapter you must extend `AbstractPlacesAutocompleteAdapter` and preserve its constructor.

https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/README.md#xml-properties

**Comment by tuanth89** [comment]
@sddamico , i use your custom adapter but still not working. i miss something ???
Here is adapter :
<pre>
public class TestPlacesAutocompleteAdapter extends AbstractPlacesAutocompleteAdapter {

    protected TestPlacesAutocompleteAdapter(final Context context, final PlacesApi api, final AutocompleteResultType resultType, final AutocompleteHistoryManager history) {
        super(context, api, resultType, history);
    }

    @Override
    protected View newView(final ViewGroup parent) {
        return LayoutInflater.from(parent.getContext()).inflate(R.layout.places_autocomplete_item, parent, false);
    }

    @Override
    protected void bindView(final View view, final Place item) {
        ((TextView) view).setText(item.description);
    }
}
</pre>

**Comment by sddamico** [comment]
Hmm, that looks right.

If you change the 4th parameter to `DefaultAutocompleteHistoryManager` does that resolve it?

**Comment by tuanth89** [comment]
@sddamico sorry for my late reply. I tried but it not woked.
I think if you can, you should create a example full about this. Thank very much :)

**Comment by sddamico** [comment]
@tuanth89 not sure if you managed to figure this out on your own, but the issue was that the constructor needed to be made `public`. This is fixed in #21, sorry about that.
