### ISSUE TITLE
FileNotFound when historyFile set to null

### ISSUE THREAD

**Issue by sddamico** [seatgeek/android-PlacesAutocompleteTextView#14]
From https://github.com/seatgeek/android-PlacesAutocompleteTextView/issues/11

```
E/MapsPlacesAutoComplete: Unable to load history from history file
E/MapsPlacesAutoComplete: java.io.FileNotFoundException: History file does not exist
E/MapsPlacesAutoComplete: at com.seatgeek.placesautocomplete.history.DefaultAutocompleteHistoryManager$1.executeInBackground(DefaultAutocompleteHistoryManager.java:68)
E/MapsPlacesAutoComplete: at com.seatgeek.placesautocomplete.history.DefaultAutocompleteHistoryManager$1.executeInBackground(DefaultAutocompleteHistoryManager.java:64)
E/MapsPlacesAutoComplete: at com.seatgeek.placesautocomplete.async.BackgroundExecutorService$2.run(BackgroundExecutorService.java:43)
E/MapsPlacesAutoComplete: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/MapsPlacesAutoComplete: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/MapsPlacesAutoComplete: at java.lang.Thread.run(Thread.java:818)
```

**Comment by MeinLieberScholli** [comment]
The problem is in the DefaultAutocompleteHistoryManager the line 36:
File historyFile = new File(context.getCacheDir(), BASE_AUTOCOMPLETE_HISTORY_DIR + historyFileName);
It won't creat the actual file in the filesystem.
Missing code is:
        if (!historyFile.exists()) {
            historyFile.mkdirs();
            try {
                historyFile.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
