### ISSUE TITLE
Not yet implemented, please have Gson on your classpath

### ISSUE THREAD

**Issue by oZBo** [seatgeek/android-PlacesAutocompleteTextView#18]
I really like your lib, great job!

But I have following exception:
`java.lang.UnsupportedOperationException: Not yet implemented, please have Gson on your classpath
                                                                 at com.seatgeek.placesautocomplete.json.AndroidPlacesApiJsonParser.autocompleteFromStream(AndroidPlacesApiJsonParser.java:15)
                                                                 at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient$1.handleStreamResult(AbstractPlacesHttpClient.java:28)
                                                                 at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient$1.handleStreamResult(AbstractPlacesHttpClient.java:24)
                                                                 at com.seatgeek.placesautocomplete.network.HttpUrlConnectionMapsHttpClient.executeNetworkRequest(HttpUrlConnectionMapsHttpClient.java:34)
                                                                 at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient.executeAutocompleteRequest(AbstractPlacesHttpClient.java:24)
                                                                 at com.seatgeek.placesautocomplete.PlacesApi.autocomplete(PlacesApi.java:147)
                                                                 at com.seatgeek.placesautocomplete.adapter.PlacesApiFilter.performFiltering(PlacesApiFilter.java:76)
                                                                 at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)`

Please tell me if You have some suggetions. Thanks in advance!

**Comment by oZBo** [comment]
my fault, forgot to add gson library to dependencies. Otherwise thanks a lot!
