### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by sarathnk** [seatgeek/android-PlacesAutocompleteTextView#25]
Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, class com.seatgeek.placesautocomplete.PlacesApi, class com.seatgeek.placesautocomplete.model.AutocompleteResultType, interface com.seatgeek.placesautocomplete.history.AutocompleteHistoryManager]
                                                                                   at java.lang.Class.getConstructorOrMethod(Class.java:423)
                                                                                   at java.lang.Class.getConstructor(Class.java:397)

**Comment by sddamico** [comment]
@sarathnk are you using proguard in your application?

**Comment by sarathnk** [comment]
No

**Comment by sddamico** [comment]
@sarathnk Can you please provide the example code for layout/activity where you're seeing this error?

**Comment by sarathnk** [comment]
I solved issue.I used custom adapter and i changed constructor then solved issue.Thanks @sddamico
