### ISSUE TITLE
Progueard rules

### ISSUE THREAD

**Issue by DimaKTheAweome** [seatgeek/android-PlacesAutocompleteTextView#27]
Hello, I use your project in my one and when I compile app with proguard I receive this error:
```
android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.seatgeek.placesautocomplete.PlacesAutocompleteTextView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
```

I tried 

-keep class com.seatgeek.** {*;}

But it doesn't help
Can you provide prgoard rules for your project?

**Comment by DimaKTheAweome** [comment]
I found problem. It was a problem with adapter which I set in xml file
