### ISSUE TITLE
Crash APK signée 

### ISSUE THREAD

**Issue by majdirabeh** [seatgeek/android-PlacesAutocompleteTextView#48]
Crash when try to enter word in TextView 
AndroidRuntime: FATAL EXCEPTION: Filter
                                                   Process: com.visitou.visitouandroid, PID: 20333
                                                   java.lang.AssertionError: java.lang.NoSuchFieldException: ROUTE
                                                       at com.google.a.b.a.n$a.<init>(Unknown Source)
                                                       at com.google.a.b.a.n$24.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.b.a.b.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.b.a.b.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.b.a.i.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.google.a.f.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.d.b.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.f.a$1.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.f.a$1.b(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.f.b.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.f.a.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.d.a(Unknown Source)
                                                       at com.seatgeek.placesautocomplete.a.c.performFiltering(Unknown Source)
                                                       at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    Caused by: java.lang.NoSuchFieldException: ROUTE
                                                       at java.lang.Class.getField(Class.java:891)
                                                       at com.google.a.b.a.n$a.<init>(Unknown Source) 
                                                       at com.google.a.b.a.n$24.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.b.a.b.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.b.a.b.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.b.a.i.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.google.a.f.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.d.b.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.f.a$1.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.f.a$1.b(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.f.b.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.f.a.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.d.a(Unknown Source) 
                                                       at com.seatgeek.placesautocomplete.a.c.performFiltering(Unknown Source) 
                                                       at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:207) 
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by sddamico** [comment]
@majdirabeh This appears to be a misconfiguration of proguard in you application. Have you tried applying rules to ensure that you're keeping this particular enum value?

**Comment by sddamico** [comment]
Closing because of no response from user.
