### ISSUE TITLE
After Enable ProGuard Issue

### ISSUE THREAD

**Issue by singhmeenu** [seatgeek/android-PlacesAutocompleteTextView#87]
`  Caused by: android.view.InflateException: Binary XML file line #65: Error inflating class com.seatgeek.placesautocomplete.PlacesAutocompleteTextView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                           at app.pnd.qrbarcode.scanner.TypeGenerateQR.onCreate(TypeGenerateQR.java:131) 
                                                                           at android.app.Activity.performCreate(Activity.java:6904) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                           at app.pnd.qrbarcode.scanner.TypeGenerateQR.onCreate(TypeGenerateQR.java:131) 
                                                                           at android.app.Activity.performCreate(Activity.java:6904) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: android.view.InflateException: Unable to find valid constructor with params Context, PlacesApi, AutocompleteResultType, and AutocompleteHistoryManager for specified adapterClass: app.pnd.qrbarcode.adapter.TestPlacesAutocompleteAdapter
                                                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.adapterForClass(PlacesAutocompleteTextView.java:301)
                                                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.init(PlacesAutocompleteTextView.java:152)
                                                                           at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.<init>(PlacesAutocompleteTextView.java:107)
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                           at app.pnd.qrbarcode.scanner.TypeGenerateQR.onCreate(TypeGenerateQR.java:131) 
                                                                           at android.app.Activity.performCreate(Activity.java:6904) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, class com.seatgeek.placesautocomplete.PlacesApi, class com.seatgeek.placesautocomplete.model.AutocompleteResultType, interface com.seatgeek.placesautocomplete.history.AutocompleteHistoryManager]
                                                                           at java.lang.Class.getConstructor(Class.java:528)
                                                                           at java.lang.Class.getConstructor(Class.java:492)`

**Comment by sddamico** [comment]
See #39 for a discussion around proguard rules
