### ISSUE TITLE
Place Options are not coming

### ISSUE THREAD

**Issue by ravigupta9363** [seatgeek/android-PlacesAutocompleteTextView#9]

**Comment by sddamico** [comment]
@ravigupta9363 can you please elaborate a bit more on the issue that you are seeing?

**Comment by ravigupta9363** [comment]
I am getting this error when I type something in place auto complete 

An exception occured during performFiltering()!
                                                              java.lang.UnsupportedOperationException: Not yet implemented, please have Gson on your classpath
                                                                  at com.seatgeek.placesautocomplete.json.AndroidPlacesApiJsonParser.autocompleteFromStream(AndroidPlacesApiJsonParser.java:15)
                                                                  at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient$1.handleStreamResult(AbstractPlacesHttpClient.java:28)
                                                                  at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient$1.handleStreamResult(AbstractPlacesHttpClient.java:24)
                                                                  at com.seatgeek.placesautocomplete.network.HttpUrlConnectionMapsHttpClient.executeNetworkRequest(HttpUrlConnectionMapsHttpClient.java:34)
                                                                  at com.seatgeek.placesautocomplete.network.AbstractPlacesHttpClient.executeAutocompleteRequest(AbstractPlacesHttpClient.java:24)
                                                                  at com.seatgeek.placesautocomplete.PlacesApi.autocomplete(PlacesApi.java:147)
                                                                  at com.seatgeek.placesautocomplete.adapter.PlacesApiFilter.performFiltering(PlacesApiFilter.java:76)
                                                                  at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                  at android.os.Looper.loop(Looper.java:189)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ravigupta9363** [comment]
You should contain the GSON library compile in gradle

**Comment by sddamico** [comment]
@ravigupta9363 You can add gson yourself, or you can wait for the merger of https://github.com/seatgeek/android-PlacesAutocompleteTextView/pull/8.
